services: 
  app: 
    build:
     context: app
     target: builder
    volumes:
      - ./files:/app/files
    ports: 
      - '5000:5000'
    command: python3 app.py
  
  test:
    build:
      context: app
      target: builder
    command: pytest tests/ -v